name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Check
      run: |
        yarn install
        yarn run lint
        yarn run test
